version: '3'

services:
  web:
    build:
      context: ./docker/php
      args:
        WWWUSER: "${WWWUSER:-1000}"
        WWWGROUP: "${WWWGROUP:-1000}"
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
  mysql:
    build: ./docker/mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
volumes:
  db:
